### ISSUE TITLE
Can't connect Mattermost Cloud to Github using plugin

### ISSUE THREAD

**Issue by hmapedro** [mattermost/mattermost-plugin-github#642] opened 2023-02-13 09:26 UTC
I have a Mattermost Cloud account for my company and I'm trying to connect it to Github. I've configured Mattermost and Github as described in https://github.com/mattermost/mattermost-plugin-github/blob/master/README.md#installation. I follow all the steps but when I go back to Mattermost and do /github connect it always says "Click here to link you GitHub account". When I click it goes to the URL "https://<my company>.cloud.mattermost.com/main/channels/github-tests" but this page never opens. Later I also receive a direct message from GitHub bot on Mattermost saying "There was an error connecting to your GitHub: Timed out waiting for OAuth connection. Please check if the SiteURL is correct. Please double check your configuration."

I don't know how to debug this as this is a cloud environment. Can anyone help?

**Comment by aaronthesourceuk** [comment] 2023-02-13 10:43
I'm still new and learning myself. I made a few mistakes in the setup which I had to debug. I got a similar issues when I set the siteURL on GitHub incorrectly

When setting up the Oauth have you double-checked that the URL you entered here matched the siteURL in your conf?
```
https://<your-mattermost-url.com>/plugins/github/oauth/complete
        ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by hmapedro** [comment] 2023-02-13 13:28
Yes. I've triple checked it. I can access https://<your-mattermost-url.com>/plugins/github/oauth/complete and I get the following message "missing authorization code".

**Comment by hmapedro** [comment] 2023-02-13 22:31
Found the solution! Changed the "Use Preregistered OAuth Application" to false. I believe this should be described on the documentation because otherwise people will most of the times use the default configuration.

**Comment by hmapedro** [comment] 2023-02-13 22:32
Found the solution! Changed the "Use Preregistered OAuth Application" to false. I believe this should be described on the documentation because otherwise people will most of the times use the default configuration.

**Comment by hanzei** [comment] 2023-02-14 03:22
@DHaussermann Can you please take a look and check if the preregistered oauth app works on Cloud for you?

**Comment by mickmister** [comment] 2023-02-14 04:32
Thanks for creating this issue @hmapedro

Note that we normally we recommend to use the preregistered app purely out of convenience for the admin. Since you have set it up yourself, I recommend going with your setup :+1:

We should make it clear in the docs that this setting needs to be `false` if the admin going to set up the OAuth app, and explain that we recommend the preregistered one on Cloud for convenience.

**Comment by DHaussermann** [comment] 2023-02-14 22:34
@hanzei and @mickmister I has double checked to ensure both the preregistered and personal oAuth apps work to authenticate. The only thing I would add not already mentioned above... 

0/5 maybe we should change the UI so that you must actively choose whether or not you want to use the pre-registered app or make one. I think this seems error prone as is. Both users above got snagged because Cloud defaults to pre-registered. What makes it even more confusing for users is that we don't grey-out the client ID and Secret when pre-registered is true. Therefore users are entering their values and it's not obvious the plugin is ignoring them.

**Comment by mickmister** [comment] 2023-02-15 14:36
@DHaussermann @hanzei Strange how the issue author is running into issues with the pre-registered app, but we can't reproduce

**Comment by hanzei** [comment] 2023-02-16 09:55
I can reproduce the issue with the pre-registered app. Reaching out to our SRE team internally, as this might be an infrasture issue: https://community.mattermost.com/private-core/pl/ac7rpi6bwbg4ijyafn4749yr7r

**Comment by hanzei** [comment] 2023-02-27 20:09
It turns it; it was indeed an infrasture issue. This has been resolved, and the pre-reistered oauth application does work now.

**Comment by Kshitij-Katiyar** [comment] 2023-10-04 10:46
@hanzei @DHaussermann @mickmister From the conversation on this issue, Should we close the issue if it is already fixed? Or is there any documentation change we still need to do.

**Comment by hanzei** [comment] 2023-10-04 11:53
@Kshitij-Katiyar We can close the issue

**Closed** 2023-10-04 11:55 UTC
