### ISSUE TITLE
User not receiving DM notifications. Had to manually run `notifications on` slash command to re-enable

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#695] opened 2023-09-08 16:40 UTC
More context in this thread https://community.mattermost.com/_redirect/pl/onhmr9wu17ybde1ezdqs6bpdjw

**Comment by Kshitij-Katiyar** [comment] 2023-09-28 10:32
@mickmister I have tried to reproduce the same on the given plugin and server version but am still not able to reproduce this. Is there any other information I can get here?

**Comment by mickmister** [comment] 2023-10-03 05:58
@Kshitij-Katiyar I'm not sure what else to go off of here. I think we should leave this open for reference, though we can close if you'd like this closed

**Comment by hanzei** [comment] 2024-07-31 12:08
Closing per https://github.com/mattermost/mattermost-plugin-github/issues/695#issuecomment-1744260315

**Closed by hanzei** 2024-07-31 12:08 UTC
Labels: Type/Bug
