### ISSUE TITLE
GitHub plugin bot in Mattermost instance is shown as GitHub Legacy bot 

### ISSUE THREAD

**Issue by cherukurisai** [mattermost/mattermost-plugin-github#641] opened 2023-02-08 14:09 UTC
Where in the system the Github bot account Plugin is displayed as GitHub (Legacy), But as per customer findings the plugin seems to be working fine.

So the customer is requesting to change the bot name to GitHub bot again and it was found to be a bug so raising this bug in the integrations team.

<img width="1000" alt="Screenshot 2023-01-31 at 6 32 53 PM" src="https://user-images.githubusercontent.com/41825284/217551987-d245bb99-075a-440b-9cce-942d710211c7.png">

<img width="856" alt="Screenshot 2023-01-31 at 6 31 52 PM" src="https://user-images.githubusercontent.com/41825284/217552014-a6c4d6b6-d541-4834-91f3-08ba1d6b144c.png">

The user is seeing this change of bot name from last year November, It's not related to the latest upgrade of Mattermost or plugin upgradation.

**Comment by m1lt0n** [comment] 2023-02-13 16:24
@cherukurisai Do we have information about the instance version? Also, did the behaviour/display name changed recently?

**Comment by cherukurisai** [comment] 2023-02-16 07:58
> @cherukurisai Do we have information about the instance version? Also, did the behavior/display name change recently?

@m1lt0n The MM Instance version is 7.1.5 and the GitHub Plugin version is 2.1.4

**Comment by mickmister** [comment] 2023-02-16 18:19
@hanzei Do you have any ideas about how this `(Legacy)` label could have been introduced? I don't see anything like this in the following repos:

- mattermost-plugin-github
- mattermost-plugin-api
- mattermost-server
- mattermost-webapp

**Comment by hanzei** [comment] 2023-02-16 20:48
@mickmister I have no idea what causes the `(legacy)` label.

**Comment by adityadav1987** [comment] 2023-03-10 06:57
@hanzei @mickmister What is the way forward here, in this case ?

**Comment by m1lt0n** [comment] 2023-03-10 08:03
Since the repos don't mark/label the bot names programmatically, could the bot name have been updated via `mmctl` by a system admin?

**Comment by mickmister** [comment] 2023-03-24 15:09
@m1lt0n I'm at a loss for how this happened here. I'm also not sure what we can do. Although it seems unlikely, the only thing that comes to mind is that someone manually changed the bot's name. Maybe a plugin they have installed that made this change?

**Comment by m1lt0n** [comment] 2023-03-24 15:11
@mickmister yes that was my only assumption too (e.g. via mmctl update bot), as I haven't found any place that we would label the bot as "legacy"

**Comment by ChristophHoyer** [comment] 2023-09-06 08:05
same issue here. We already opened a ticket (39066) and are waiting for a solution since January. Must be a pretty hard issue.

**Comment by ayusht2810** [comment] 2024-04-04 08:36
@mickmister I tried to reproduce the error in the versions mentioned above but was not able to. Should we close the issue now, or do we need to look more into this?

**Closed** 2024-04-23 20:50 UTC
