### ISSUE TITLE
Comments on updated PR's are reported incorrectly by the plugin

### ISSUE THREAD

**Issue by reflog** [mattermost/mattermost-plugin-github#193] opened 2020-02-17 08:17 UTC
This is a regression, previously the text of the comment was reported, now it just shows: ">"

![image](https://user-images.githubusercontent.com/109876/74635414-a08bf280-516e-11ea-9182-2aa28b3f7f75.png)

**Comment by levb** [comment] 2020-02-18 12:27
@jfrerich can you please investigate?

**Comment by hanzei** [comment] 2020-02-18 13:44
@reflog Is this related to https://github.com/mattermost/mattermost-plugin-github/issues/185?

**Comment by jfrerich** [comment] 2020-02-18 18:29
Thanks @hanzei.  I would suspect that issue and the following pull request are causing the missing comments.
https://github.com/mattermost/mattermost-plugin-github/pull/187/files

**Comment by reflog** [comment] 2020-02-18 20:24
@hanzei spot on!

**Comment by hanzei** [comment] 2020-02-19 15:59
Closing as a duplicate of https://github.com/mattermost/mattermost-plugin-github/issues/185

**Closed by hanzei** 2020-02-19 15:59 UTC
Labels: Bug, Triage
