### ISSUE TITLE
new-issue  not display  notification if subscribe labels

### ISSUE THREAD

**Issue by sunhaolin** [mattermost/mattermost-plugin-github#334] opened 2020-07-23 04:02 UTC
`/github subscribe sunhaolin/sunhaolin.github.io issues,label:"done"`
not display new-issue  notification

when remove `label:"done"`
` /github subscribe sunhaolin/sunhaolin.github.io issues`  display new-issue  notification

**Comment by Kshitij-Katiyar** [comment] 2024-07-10 05:49
@wiggin77 @sunhaolin  I explored this issue and found that it is not reproducible if a new issue on GitHub is created with the label used during the subscription creation. The issue is only reproducible when the GitHub issue does not use the label specified during the subscription creation.
Here is the [link](https://github.com/mattermost/mattermost-plugin-github/blob/4ae160314e0033c0868b171563de412d05e7717f/server/plugin/webhook.go#L624) to the code related to the functionality.

**Comment by raghavaggarwal2308** [comment] 2024-07-16 14:31
@sunhaolin Closing this issue for now. Please let us know if are still facing the issue.

**Closed by raghavaggarwal2308** 2024-07-16 14:31 UTC
Labels: Type/Bug
