### ISSUE TITLE
@mention on your PR or Issue should supercede muted user comments 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-github#386] opened 2020-10-08 04:38 UTC
There is now a mute list to prevent DM notification when users on the mute list comment on your PRs or issues.

When a user who is on your mute list @mentions you on one of your own issues or PR no notification DM is received.
The functionality of delivering @mentions should take precedence here even though the users's comment would otherwise be muted if it did not contain the at mention.

**note**: The issue can only be observed when adding a mention on a PR or issue that is assigned to the test user. In other cases @ mentions are working as expected and the mute list causes no problems.  

Steps:
- Connect test user to GitHub
- Add another user - _UserB_ to your mute list
- Login to Guthub as _UserB_  
- Locate a PR or issue the test user is assigned to
- Comment on the issue with an at mention for the test user

**Observed**: No DM received by the test user as _UserB_ is muted 
**Expected**: At mention should be delivered regardless

**Comment by hanzei** [comment] 2020-10-08 09:25
@DHaussermann That behaviour is by design. The documentation for the mute features reads: `You will not receive notifications for comments in your PRs and issues from those users.`. Maybe it should be made more clear that this also includes PRs and issues a users is _assigned_ to. But I think the documentation makes clear that it's not only about @-mentions.

**Comment by DHaussermann** [comment] 2020-10-08 14:06
Thanks @hanzei, I thought @ mentions would be treated differently from other comments. Are we sure we want to block @mentons as well? This seems to be mostly to block automated tooling so, I'm not sure if blocking @ mentions is something needed.

**Comment by hanzei** [comment] 2020-10-08 15:15
I'm inclined to say yes. @nickmisasi What do you think about this?

**Comment by nickmisasi** [comment] 2020-10-08 15:23
Hello! My intention with the mute command was to _not_ block notifications for @ mentions. I'm pretty sure with the current behaviour, if a muted person/bot @mentions you from an issue/PR that isn't your own, you will still get that notification. 

I think that behaviour should be consistent across everything. If someone @ mentions you, it's probably important. So I tend to agree with @DHaussermann that @ mentions should take preference.

**Comment by hanzei** [comment] 2020-10-08 15:33
Is it common for bot/integrations to @-mention someone? If so, we should block it, if not I'm leaning towards no.

E.g. Mattermod @-mentions people for cherry-picks which doesn't seem important to me.

**Comment by nickmisasi** [comment] 2020-10-08 16:26
I agree bot/integrations @ mention is probably not a very common thing.  I'm 0/5 on which way it should be, I see advantages to both. I think whatever way we choose should be consistent across all cases to avoid confusion. 

There is potential for people using this mute functionality on non-bots. So that could be something to keep in mind.

**Comment by raghavaggarwal2308** [comment] 2024-07-13 11:56
@hanzei Have we concluded what should be the the functionality here? Can we close this issue if the current behaviour looks fine? 
Another related issue: https://github.com/mattermost/mattermost-plugin-github/issues/543

**Comment by hanzei** [comment] 2024-07-29 14:00
I'm inclined to close both tickets as won't do. The mute feature works as documented; it mutes all notifications from a given user.

**Closed** 2024-07-30 08:03 UTC
Labels: Type/Enhancement
