### ISSUE TITLE
Support being able to only subscribe to issue creation, and not issues being closed

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#390] opened 2020-10-16 13:31 UTC
Currently when you make a subscription such as `/github subscriptions add (org/repo) issues`:

- a post is created when a new issue is created
- a post is created when an issue is closed

The goal here is to support subscribing to issue creation only. This should be a backwards compatible fix by requiring a separate argument like `issue_creation` instead of `issues`

**Comment by Remakh** [comment] 2020-10-16 17:33
Mind if I try?

**Comment by mickmister** [comment] 2020-10-16 17:37
> Mind if I try?

Absolutely! Thanks @Remakh!!

**Comment by Remakh** [comment] 2020-10-16 19:06
Any hints on where I could start? I've committed some stuff but I'm not too sure about it

**Comment by mickmister** [comment] 2020-10-16 19:07
@Remakh Do you have any specific questions? Maybe you can submit a draft PR for discussion if you'd like?

**Comment by Remakh** [comment] 2020-10-16 19:12
Sure I'll do that

**Comment by Remakh** [comment] 2020-10-16 19:25
I created a draft PR as you suggested. I was wondering where in the repo the code for creating posts is? I assumed I would create a new function mostly identical to the one that posts when subscribed to issues, but instead only posts when an issue is created. Am I wrong in this assumption?

**Comment by mickmister** [comment] 2020-10-16 19:55
> I assumed I would create a new function mostly identical to the one that posts when subscribed to issues, but instead only posts when an issue is created. Am I wrong in this assumption?

@Remakh Are you saying that the posts are not being created when issues are closed, and only when they are initially opened?

**Comment by Remakh** [comment] 2020-10-16 20:05
> > I assumed I would create a new function mostly identical to the one that posts when subscribed to issues, but instead only posts when an issue is created. Am I wrong in this assumption?
> 
> @Remakh Are you saying that the posts are not being created when issues are closed, and only when they are initially opened?

Yes, unless I'm misunderstanding the issue? The issue is that if you subscribe to issues, a post is created when an issue opens or closes, and there should be a subscription option so that posts are only created when issues open, correct? I was wondering if you could indicate where these posts are created in the codebase, so I could modify it so posts aren't created when issues closed.

**Comment by mickmister** [comment] 2020-10-16 20:11
@Remakh Looks like we do some processing of that here https://github.com/mattermost/mattermost-plugin-github/blob/793631adb358f29a7d1a187dfedd13c2d5dfdf11/server/plugin/webhook.go#L351-L364

The fix is likely somewhere below this section in the same function

**Comment by Remakh** [comment] 2020-10-16 21:25
thanks for your help. I tried to solve it, and hope this solution will work

**Closed** 2020-11-06 18:03 UTC
Labels: Difficulty/1:Easy, Good First Issue, Hacktoberfest, Help Wanted, Tech/Go, Type/Enhancement
