### ISSUE TITLE
On community-daily, some GitHub plugin API requests from webapp are returning 500s

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-github#387] opened 2020-10-10 21:03 UTC
All requests are working fine on community-release.

Consistently on daily:

- `reviews` and `yourprs` succeeds
- `unreads` and `yourassignments` fails

Some pr and issue fetches for the tooltips fail, and some succeed. It seems the ones failing are consistently failing. Between daily and release, the requests look identical for each fetch.

Update after discussion with the team:
The 200s may be cached. We need to investigate more into this, possibly look at logs between dailt versus release.

<img width="400px" src="https://user-images.githubusercontent.com/6913320/95664945-ee98a080-0b19-11eb-9eca-acb2bb55fbbe.png" />

**Comment by hanzei** [comment] 2020-10-12 08:34
Please see my response on Community: https://community-daily.mattermost.com/core/pl/8r995qzcx7yd8cuh4dt114st6o

**Comment by mickmister** [comment] 2020-10-15 17:12
I'm not seeing the issue anymore after the 2.0.0 (I think) release on community. Our requests are a lot less spammy now for the tooltips. We now only fetch the PR info after the user has actually hovered over the link, rather than on component mount. I'm thinking we should close this cc @hanzei

**Comment by mickmister** [comment] 2020-10-15 17:13
I have re-raised the issue in a relevant thread [here](https://community-daily.mattermost.com/core/pl/grtm1616nfntdr5sthx1x7rcwe)

**Comment by hanzei** [comment] 2020-10-16 09:42
It seems concerning to me, if the high number of requests caused an issue in the Mattermost Server. That is something that the server should handle. 

Does it make sense to forcefully try to reproduce this issue by building a custom plugin that launches a lot of requests?

**Comment by mickmister** [comment] 2020-10-16 21:07
@hanzei Sure is this something you would be interested in doing?

**Comment by catalintomai** [comment] 2020-10-19 19:09
@iomodo , would this be an addition/ good fit to your test plugin?

**Comment by iomodo** [comment] 2020-10-19 19:57
@catalintomai `test-plugin` is for e2e tests. Are you suggesting creating an e2e test to repro this?

**Comment by catalintomai** [comment] 2020-10-19 20:01
> @catalintomai `test-plugin` is for e2e tests. Are you suggesting creating an e2e test to repro this?

There was some discussion in today's Backlog Grooming meeting wrt to the right place to add this kind of stress test(?). Your test plugin was discussed as a possibility it if makes sense cc: @DHaussermann

**Comment by hanzei** [comment] 2020-11-12 12:30
I've filled https://mattermost.atlassian.net/browse/MM-30474 to capture the effort of stress testing the plugin framework. During that effort the root cause of this issue might be found. I'm going to close it for now.

**Closed by hanzei** 2020-11-12 12:30 UTC
Labels: Type/Bug
